version: '3.4'

services:

  nginx:
    build:
      context : ./nginx/
    depends_on:
      - frontend
      - server-get
      - server-post
      - server-put
      - server-delete
    ports:
      - "80:80"
    environment:
      - DATABASE_URI=${DATABASE_URI}

  frontend:
    build: 
      context: .
    environment:
      - DATABASE_URI=${DATABASE_URI}

  server-get:
    build: 
       context: .
    environment:
      - DATABASE_URI=${DATABASE_URI}

  server-post:
    build: 
      context: .
    environment:
      - DATABASE_URI=${DATABASE_URI}

  server-put:
    build: 
       context: .
    environment:
      - DATABASE_URI=${DATABASE_URI}
    
  server-delete:
    build: 
       context: .
    environment:
      - DATABASE_URI=${DATABASE_URI}